# **PART1-DATA PREPROCESSING**

In [1]:
#Load the Dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import sklearn

In [2]:
data=pd.read_csv("../dataset/employee_performance.csv")

In [3]:
data.head()

,Employee_ID,Age,Gender,Department,Experience_Years,Performance_Score,Salary
0,E0524,49,Female,Operations,5.6,67.8,33013.0
1,E0603,55,Female,Sales,5.5,NaN,42640.0
2,E0527,29,Female,Sales,10.7,68.8,72180.0
3,E0032,30,Female,Operations,9.8,NaN,65750.0
4,E0617,58,Male,Sales,11.5,72.8,74830.0

In [4]:
#Handle Missing Values
data.isnull().sum()

Employee_ID           0
Age                   0
Gender                0
Department            0
Experience_Years     32
Performance_Score    30
Salary                0
dtype: int64

In [5]:
data['Experience_Years'] = data['Experience_Years'].fillna(
    data['Experience_Years'].median())
data['Performance_Score'] = data['Performance_Score'].fillna(
    data['Performance_Score'].median()
)

In [6]:
# Remove Duplicates
data.isnull().sum()

Employee_ID          0
Age                  0
Gender               0
Department           0
Experience_Years     0
Performance_Score    0
Salary               0
dtype: int64

In [7]:
#Remove Duplicates
data.duplicated().sum()

np.int64(20)

In [8]:
data=data.drop_duplicates()

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
# Encode Categorical Features
data.select_dtypes(include='object').columns

Index(['Employee_ID', 'Gender', 'Department'], dtype='object')

In [11]:
data=pd.get_dummies(data,
                    columns=['Gender','Department'],
                    drop_first=True,
                    dtype=int)

In [12]:
data.head()

,Employee_ID,Age,Experience_Years,Performance_Score,Salary,Gender_Male,Department_HR,Department_IT,Department_Marketing,Department_Operations,Department_Sales
0,E0524,49,5.6,67.80,33013.0,0,0,0,0,1,0
1,E0603,55,5.5,70.05,42640.0,0,0,0,0,0,1
2,E0527,29,10.7,68.80,72180.0,0,0,0,0,0,1
3,E0032,30,9.8,70.05,65750.0,0,0,0,0,1,0
4,E0617,58,11.5,72.80,74830.0,1,0,0,0,0,1

In [13]:
# Scale Numerical Features
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
data[['Age','Experience_Years','Performance_Score']] = scaler.fit_transform(
    data[['Age','Experience_Years','Performance_Score']])

In [14]:
data[['Age','Experience_Years','Performance_Score']].head()

        Age  Experience_Years  Performance_Score
0  0.721901         -0.534641          -0.205237
1  1.259763         -0.567688           0.024804
2 -1.070973          1.150777          -0.102997
3 -0.981329          0.853350           0.024804
4  1.528694          1.415156           0.305964

In [15]:
#Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X= data.drop(['Employee_ID','Salary'],axis=1)
Y=data['Salary']
X_train,X_test,Y_train,Y_test=train_test_split(
    X,Y,test_size=0.2,
random_state=42)

In [16]:
print(X_train.shape)

(800, 9)

In [17]:
print(X_test.shape)

(200, 9)

In [18]:
print(Y_train.shape)

(800,)

In [19]:
print(Y_test.shape)

(200,)

# **PART 2-MODEL DEVELOPMENT**

In [20]:
# Linear Regression
from sklearn.linear_model import LinearRegression
model_1r=LinearRegression()
model_1r.fit(X_train,Y_train)

LinearRegression()

In [21]:
# Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
model_dt=DecisionTreeRegressor(random_state=42)
model_dt.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=42)

In [22]:
# Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
model_rf=RandomForestRegressor(random_state=42)
model_rf.fit(X_train,Y_train)

RandomForestRegressor(random_state=42)

# **PART 3-MODEL EVALUATION**

In [23]:
Y_pred_1r=model_1r.predict(X_test)
Y_pred_dt=model_dt.predict(X_test)
Y_pred_rf=model_rf.predict(X_test)

In [24]:
# MAE
from sklearn.metrics import mean_absolute_error
mae_1r=mean_absolute_error(Y_test,Y_pred_1r)
mae_dt=mean_absolute_error(Y_test,Y_pred_dt)
mae_rf=mean_absolute_error(Y_test,Y_pred_rf)
print("Linear Regression MAE:",mae_1r)
print("Decision Tree MAE:",mae_dt)
print("Random Forest MAE:",mae_rf)

Linear Regression MAE: 5928.79386120792
Decision Tree MAE: 14273.8
Random Forest MAE: 7024.231749999999

In [25]:
#MSE
from sklearn.metrics import mean_squared_error
mse_1r=mean_squared_error(Y_test,Y_pred_1r)
mse_dt=mean_squared_error(Y_test,Y_pred_dt)
mse_rf=mean_squared_error(Y_test,Y_pred_rf)
print("Linear Regression MSE:",mse_1r)
print("Decision Tree MSE:",mse_dt)
print("Random Forest MSE:",mse_rf)

Linear Regression MSE: 57656979.672331944
Decision Tree MSE: 2425817245.71
Random Forest MSE: 183504840.26594654

In [26]:
#RMSE
import numpy as np
rmse_1r=np.sqrt(mse_1r)
rmse_dt=np.sqrt(mse_dt)
rmse_rf=np.sqrt(mse_rf)
print("Linear Regression RMSE:",rmse_1r)
print("Decision Tree RMSE:",rmse_dt)
print("Random Forest RMSE:",rmse_rf)

Linear Regression RMSE: 7593.219322022243
Decision Tree RMSE: 49252.58618296099
Random Forest RMSE: 13546.395840442081

In [27]:
# R^2 Score
from sklearn.metrics import r2_score
r2_1r=r2_score(Y_test,Y_pred_1r)
r2_dt=r2_score(Y_test,Y_pred_dt)
r2_rf=r2_score(Y_test,Y_pred_rf)
print("Linear Regression R2 Score:",r2_1r)
print("Decision Tree R2 Score:",r2_dt)
print("Random Forest R2 Score:",r2_rf)

Linear Regression R2 Score: 0.7206246623684782
Decision Tree R2 Score: -10.754231940418766
Random Forest R2 Score: 0.1108322531345004

# **PART4-MODLE COMPARISON**

In [28]:
# Training Time + Comparison Table
import time
start = time.time()
model_1r.fit(X_train, Y_train)
time_1r = time.time() - start
start = time.time()
model_dt.fit(X_train, Y_train)
time_dt = time.time() - start
start = time.time()
model_rf.fit(X_train, Y_train)
time_rf = time.time() - start
print("Linear Regression Training Time:", time_1r)
print("Decision Tree Training Time:", time_dt)
print("Random Forest Training Time:", time_rf)

Linear Regression Training Time: 0.0041828155517578125
Decision Tree Training Time: 0.011006832122802734
Random Forest Training Time: 0.8630688190460205

In [29]:
#Model Comparison Table
comparison = {
    "Model Name": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest" ],
    "MAE": [
        mae_1r,
        mae_dt,
        mae_rf ],
    "MSE": [
        mse_1r,
        mse_dt,
        mse_rf],
    "RMSE": [
        rmse_1r,
        rmse_dt,
        rmse_rf ],
    "R2 Score": [
        r2_1r,
        r2_dt,
        r2_rf],
    "Training Time": [
        time_1r,
        time_dt,
        time_rf]
}

comparison

{'Model Name': ['Linear Regression', 'Decision Tree', 'Random Forest'],
 'MAE': [5928.79386120792, 14273.8, 7024.231749999999],
 'MSE': [57656979.672331944, 2425817245.71, 183504840.26594654],
 'RMSE': [np.float64(7593.219322022243),
  np.float64(49252.58618296099),
  np.float64(13546.395840442081)],
 'R2 Score': [0.7206246623684782, -10.754231940418766, 0.1108322531345004],
 'Training Time': [0.0041828155517578125,
  0.011006832122802734,
  0.8630688190460205]}

In [30]:
#Advantages & Limitations
comparison["Advantages"] = [
    "Simple and fast",
    "Easy to understand",
    "Good prediction performance"]
comparison["Limitations"] = [
    "Assumes linear relationship",
    "Can overfit",
    "More complex and slower"]

comparison

{'Model Name': ['Linear Regression', 'Decision Tree', 'Random Forest'],
 'MAE': [5928.79386120792, 14273.8, 7024.231749999999],
 'MSE': [57656979.672331944, 2425817245.71, 183504840.26594654],
 'RMSE': [np.float64(7593.219322022243),
  np.float64(49252.58618296099),
  np.float64(13546.395840442081)],
 'R2 Score': [0.7206246623684782, -10.754231940418766, 0.1108322531345004],
 'Training Time': [0.0041828155517578125,
  0.011006832122802734,
  0.8630688190460205],
 'Advantages': ['Simple and fast',
  'Easy to understand',
  'Good prediction performance'],
 'Limitations': ['Assumes linear relationship',
  'Can overfit',
  'More complex and slower']}

In [31]:
#Best Model Finding
print("Linear Regression R2:", r2_1r)
print("Decision Tree R2:", r2_dt)
print("Random Forest R2:", r2_rf)

Linear Regression R2: 0.7206246623684782
Decision Tree R2: -10.754231940418766
Random Forest R2: 0.1108322531345004

# **PART5-CONCLUSION**

In this project, three machine learning regression models were developed to predict
employee salary: Linear Regression, Decision Tree, and Random Forest. The dataset was
preprocessed by handling missing values,removing duplicate records,encoding categorical
features, scaling numerical features, and splitting the data into training and testing sets.

The models were evaluated using MAE, MSE, RMSE, and R^2 Score. Among the three models,
Linear Regression performed the best based on the R^2 Score of 0.7206. Random Forest
achieved an R^2 Score of 0.1108, while Decision Tree achieved -10.7542. Therefore,
Linear Regression is recommended as the best-performing model for this dataset because
it provided the strongest overall predictive performance among the tested models.